import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Link from "next/link";
import Navbar from "@/components/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-wrap lg:h-screen h-full w-full  py-5  bg-[#111111]">
          <div className="w-full sm:w-full md:w-full lg:w-full xl:w-[30%]  m-4 bg-[#1E1E1F]  rounded-lg">
            <Sidebar />
          </div>

          <div className="w-full sm:w-full md:w-full lg:w-full xl:w-[67%] m-4   bg-[#1E1E1F]  rounded-lg">
            <Navbar />
            <div className="p-5">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
